### ISSUE TITLE
A few typos I noticed, while working through the course 😇

### ISSUE THREAD

**Issue by sorenfrederiksen** [kadikraman/intermediate-react-native-v2-course-app#1]
Hey there,

I've really enjoyed your React Native content. This evening I noticed, while working through round two of the "Intermediate" course and accompanying materials, a few minor typos.

I hope you don't mind me raising them here, so you might correct them:

## Issue: Typo `Cerate` -> `Create`

<img width="729" alt="8  Cerate a _layout file" src="https://github.com/user-attachments/assets/dc3c08e6-dfd4-47d1-bcc6-04c601488b4a">

[Link](https://kadikraman.github.io/intermediate-react-native-v2-course/docs/navigation/4-1-install-navigation)

## Issue: Typo `the las big bit` -> `the last big bit`

<img width="731" alt="Dynamic routes" src="https://github.com/user-attachments/assets/2d682f9a-b792-4889-9484-eb4f8c9ea756">

[Link](https://kadikraman.github.io/intermediate-react-native-v2-course/docs/dynamic-routes)

## Issue (for some users): Not entirely clear if this needs to be on root of `app.json`, or under `expo`

**This is only an issue when you're not also watching the course videos**. The videos make this clear, but if you're interested in making the material clear in their absence, you might want to tweak this.

<img width="743" alt="3  Modify project config" src="https://github.com/user-attachments/assets/9d46cd9a-c20b-4165-bab1-25b5a6fc3e51">

[Link](https://kadikraman.github.io/intermediate-react-native-v2-course/docs/navigation/4-1-install-navigation)

Keep up the great work. Will add a comment, if I notice anything else 🫡

**Comment by kadikraman** [comment]
Hi @sorenfrederiksen - thanks for taking the time to point these out. I've updated the course website 😊
