### ISSUE TITLE
Execution failed for task ':expo-quick-actions:compileDebugKotlin'.

### ISSUE THREAD

**Issue by osama20200071** [kadikraman/intermediate-react-native-v2-course-app#2]
After adding this `expo-quick-actions` package , i got this problem and **i searched a lot but found no solution .**

**Comment by kadikraman** [comment]
Hi @osama20200071 - sorry I missed your questions. It's been 3 weeks so hopefully you've found a solution.

For future reference, the [Expo Discord](https://discord.com/invite/expo) is a good place to find answers to common Expo and React Native build errors.
